### ISSUE TITLE
Please consider adding a License

### ISSUE THREAD

**Issue by soldni** [ffaisal93/SD-QA#1]
Hi all,

First of all, congrats on the very nice work and thank you for distributing this wonderful resource! 

Second, would you mind considering adding a license (e.g., [CC-BY-SA 4.0](https://choosealicense.com/licenses/cc-by-sa-4.0/) is widely used for data releases). Per GitHub Terms and Conditions, researchers are technically not allowed to re-use any code/data from repositories unless a license is provided. 

Thank you!

Best,
Luca

**Comment by antonisa** [comment]
You're absolutely right, thanks Luca! I'll add a license shortly ;)
